services:
  db:
    image: postgres
    restart: always
    # postgres needs more shared memory, MOAR
    shm_size: 128mb
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build: .
    ports:
      - 8000:8000
    # yes, yes, I should use secret files instead, but not now
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        # restart cooldown, if project was resurrected and then died again
        # wait for 10 seconds before restarting it
        delay: 10s
    develop:
      watch:
        # restart the container on changes to entrypoint script
        - action: sync+restart
          path: ./scripts/entrypoint_docker.sh
          target: /app/scripts/entrypoint_docker.sh

        # rebuild the image if uv.lock changes
        - action: rebuild
          path: ./uv.lock

        # rebuild the image if Dockefile changes
        # how tf this isn't the default?
        - action: rebuild
          path: ./Dockerfile

        # same as above
        - action: rebuild
          path: ./docker-compose.yml

        # runserver has hot-reload, so sync will do
        #
        # gunicorn has it too, if you configure it, but it doesn't seem to
        # support hot-reloading for static files
        - action: sync
          path: .
          target: /app
          # exclude virtual environment, because it's platform-specific
          ignore:
            - .venv/

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

volumes:
  database:
