services:
  db:
    image: postgres
    restart: always
    # postgres needs more shared memory, MOAR
    shm_size: 128mb
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web-proxy:
    build: .
    ports:
      - 8000:8000
      # docker build hates me for this, but docker-compose doesn't seem to mind
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        # restart cooldown, if project was resurrected and then died again
        # wait for 10 seconds before restarting it
        delay: 10s
    develop:
      watch:
        # runserver has hot-reload, so sync will do
        #
        # use sync+restart if you want to use gunicorn
        - action: sync
          path: .
          target: /app
          # exclude virtual environment, because it's platform-specific
          ignore:
            - .venv/

        - action: sync+restart
          path: ./serve_script.sh
          target: /app/serve_script.sh

        # rebuild the image if uv.lock changes
        #
        # we would probably want either rebuild or sync+restart if we need
        # to re-collect static files
        #
        # or just develop with DEBUG enabled, idk
        - action: rebuild
          path: ./uv.lock

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080

volumes:
  database:
