databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: juliancoffee-django-blog
    runtime: python
    buildCommand: "python -m gunicorn -w 4 mysite.wsgi --bind 0.0.0.0:8000"
    envVars:
      - key: SECRET_KEY
      - key: DB_HOST
      - key: DB_PASSWORD
