# Generated by Django 5.1.3 on 2024-12-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_ip',
            field=models.CharField(default='<anon>', max_length=100),
        ),
    ]
