# Generated by Django 5.1.3 on 2025-01-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_comment_commenter_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="commenter_username",
            field=models.CharField(default="<anon>", max_length=150),
        ),
    ]
