# Generated by Django 5.1.3 on 2025-01-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_commenter_username_comment_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_ip_new',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
