# Generated by Django 5.1.3 on 2025-01-30 21:38

from django.db import migrations


def migrate_to_proper_ip(apps, _schema_editor):
    # NOTE: we're using apps registry because ...
    #
    # Well, if we use import instead, who knows that code we have at that
    # point.
    #
    # app registry makes it proper ... somehow
    # I'd guess it uses datatabase queries for that?
    #
    # well, I couldn't figure it out, I guess I may check source code
    # later
    #
    # TODO: what I did find is that turns out I should place all my models
    # in application root at models.py or models/__init__.py otherwise ORM
    # may break ... so yeah, I should fix it ^^'
    Comment = apps.get_model('blog', 'Comment')
    for comment in Comment.objects.all():
        # anyway this code is pretty straightforward
        #
        # if we had "<anon>" here, just place None
        # if we had a proper ip instead, just copy it
        #
        # ORM should properly convert all the types, yes? yes?
        #
        # I hope I won't forget to update this comment when I'll test it
        #
        # UPD: it seems to erase it anyway, why ...
        if comment.commenter_ip == "<anon>":
            comment.commenter_ip_new = None
        else:
            comment.commenter_ip_new = comment.commenter_ip

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_commenter_ip_new'),
    ]

    operations = [
        # RunPython to execute dynamic python code
        #
        # Django won't even show SQL for that, because ... yeah
        migrations.RunPython(migrate_to_proper_ip)
    ]
