# Generated by Django 5.1.3 on 2025-01-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_commenter_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_ip_new',
            new_name='commenter_ip',
        ),
    ]
