# Generated by Django 5.1.3 on 2025-04-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_rename_commenter_ip_new_comment_commenter_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commenter_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
