# Generated by Django 5.1.3 on 2025-04-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_comment_commenter_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.CharField(max_length=1000),
        ),
    ]
