# Generated by Django 5.1.3 on 2025-04-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_comment_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_text",
            field=models.CharField(max_length=10000),
        ),
    ]
