name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.7"

      - name: Generate dependency file
        run: uv pip compile pyproject.toml > requirements.txt

      - name: Commit dependency file
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add requirements.txt
          git commit -m "Generated requirements.txt" || true
          git push
    # this one is needed for `git push` to work
    permissions:
      contents: write
