name: Test

on: [pull_request]

env:
  SECRET_KEY: "very secret key"
  DB_PASSWORD: "very secret password"
  DB_HOST: "very secret host"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.7"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run manage.py test
